language: node_js
node_js:
  - "0.8"
  - "0.10"
install: npm install --save-dev
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq g++ libssl-dev gnome-keyring libgnome-keyring-dev
 - npm i -g jasmine-node node-gyp
 - mkdir ./tmp_node_modules
 - mv ./node_modules/*.js ./tmp_node_modules/
before_script:
 - mv ./tmp_node_modules/* ./node_modules/
 - rm -rf ./tmp_node_modules/
